export const courseMapper = {
  'Bachelor of Science in Civil Engineering': 'Civil Engineering',
  'Bachelor of Science in Software Engineering': 'Software Engineering',
  'Bachelor of Science in Mechatronics': 'Mechatronics',
  'Bachelor of Science in Structural Engineering': 'Structural Engineering',
  'Bachelor of Science in Chemical Engineering': 'Chemical Engineering',
  'Bachelor of Science in Marine Engineering': 'Marine Engineering',
  'Bachelor of Science in Electrical Power Engineering': 'Electrical Power Engineering',
  'Bachelor of Science in Telecommunications Engineering': 'Telecommunications Engineering',
  'Bachelor of Science in Physics with Astrophysics': 'Physics with Astrophysics',
  'Bachelor of Science in Nanotechnology': 'Nanotechnology',
  'Bachelor of Science in Statistics': 'Statistics',
  'Bachelor of Science in Molecular Biology': 'Molecular Biology',
  'Bachelor of Science in Geoinformatics': 'Geoinformatics',
  'Bachelor of Science in Climate Studies': 'Climate Studies',
  'Bachelor of Science in Earth Sciences': 'Earth Sciences',
  'Bachelor of Science in Microbiology': 'Microbiology',
  'Bachelor of Science in Urban and Regional Planning': 'Urban and Regional Planning',
  'Bachelor of Arts in English and Comparative Literature': 'English and Comparative Literature',
  'Bachelor of Arts in International Development': 'International Development',
  'Bachelor of Arts in Film and Media Studies': 'Film and Media Studies',
  'Master of Science in Aerospace Dynamics': 'Aerospace Dynamics',
  'Master of Science in Offshore Engineering': 'Offshore Engineering',
  'Master of Science in Electronics and Communication': 'Electronics and Communication',
  'Master of Science in Photonics': 'Photonics',
  'Master of Science in Embedded Systems': 'Embedded Systems',
  'Master of Science in Data Engineering and Management': 'Data Engineering and Management',
  'Master of Science in Artificial Intelligence for Healthcare': 'Artificial Intelligence for Healthcare',
  'Master of Science in Robotics and Intelligent Systems': 'Robotics and Intelligent Systems',
  'Master of Science in Nanotechnology and Nanomaterials': 'Nanotechnology and Nanomaterials',
  'Master of Science in Applied Mathematics': 'Applied Mathematics',
  'Master of Science in Actuarial Science': 'Actuarial Science',
  'Master of Science in Geospatial Science and Remote Sensing': 'Geospatial Science and Remote Sensing',
  'Master of Science in Environmental Risk Management': 'Environmental Risk Management',
  'Master of Science in Climate Change and Sustainability': 'Climate Change and Sustainability',
  'Master of Science in Advanced Automotive Engineering': 'Advanced Automotive Engineering',
  'Master of Science in Food Science and Engineering': 'Food Science and Engineering',
  'Master of Science in Renewable Energy Technology': 'Renewable Energy Technology',
  'Master of Arts in Contemporary History': 'Contemporary History',
  'Master of Arts in Philosophy of Science': 'Philosophy of Science',
  'Master of Arts in Language and Linguistics': 'Language and Linguistics',
  'Diploma in Construction Engineering': 'Construction Engineering',
  'Diploma in Petroleum Engineering': 'Petroleum Engineering',
  'Diploma in Renewable Energy Engineering': 'Renewable Energy Engineering',
  'Diploma in Instrumentation and Control Engineering': 'Instrumentation and Control Engineering',
  'Diploma in Materials Technology': 'Materials Technology',
  'Diploma in Railway Engineering': 'Railway Engineering',
  'Diploma in Water Resource Management': 'Water Resource Management',
  'Diploma in Disaster Risk Reduction': 'Disaster Risk Reduction',
  'Diploma in Wildlife Conservation and Management': 'Wildlife Conservation and Management',
  'Diploma in Graphic Design and Visual Communication': 'Graphic Design and Visual Communication',
  'Diploma in Hotel Management': 'Hotel Management',
  'Diploma in Culinary Arts and Food Technology': 'Culinary Arts and Food Technology',
  'Diploma in Textile and Apparel Design': 'Textile and Apparel Design',
  'Diploma in Fashion Technology': 'Fashion Technology',
  'Diploma in Animation and Multimedia': 'Animation and Multimedia',
  'Diploma in Fine Arts and Design': 'Fine Arts and Design',
  'Diploma in Music Technology': 'Music Technology',
  'Diploma in Film Production': 'Film Production',
  'Diploma in Public Health': 'Public Health',
  'Diploma in Education Leadership': 'Education Leadership',
  'Postgraduate Diploma in Business Analytics and Big Data': 'Business Analytics and Big Data',
  'Postgraduate Diploma in Operations Research': 'Operations Research',
  'Postgraduate Diploma in Financial Technology (FinTech)': 'Financial Technology (FinTech)',
  'Postgraduate Diploma in Supply Chain Analytics': 'Supply Chain Analytics',
  'Postgraduate Diploma in Urban Development and Planning': 'Urban Development and Planning',
  'Postgraduate Diploma in Environmental Monitoring': 'Environmental Monitoring',
  'Postgraduate Diploma in Sustainable Agriculture': 'Sustainable Agriculture',
  'Postgraduate Diploma in Cyber Law and IT Security': 'Cyber Law and IT Security',
  'Postgraduate Diploma in Innovation and Intellectual Property Rights': 'Innovation and Intellectual Property Rights',
  'Postgraduate Diploma in Creative Writing and Journalism': 'Creative Writing and Journalism',
  'Postgraduate Diploma in Cognitive Psychology': 'Cognitive Psychology',
  'Postgraduate Diploma in Machine Learning Applications': 'Machine Learning Applications',
  'Postgraduate Diploma in Human-Computer Interaction': 'Human-Computer Interaction',
  'Postgraduate Diploma in Medical Imaging and Diagnostics': 'Medical Imaging and Diagnostics',
  'Postgraduate Diploma in Social Work and Welfare Policies': 'Social Work and Welfare Policies',
  'Postgraduate Diploma in International Relations and Diplomacy': 'International Relations and Diplomacy',
  'Postgraduate Diploma in Artificial Intelligence and Robotics': 'Artificial Intelligence and Robotics',
  'Postgraduate Diploma in Marine Science and Oceanography': 'Marine Science and Oceanography',
  'Postgraduate Diploma in Disaster Management and Resilience': 'Disaster Management and Resilience',
  'Postgraduate Diploma in Educational Technology': 'Educational Technology',
  'Diploma in Computer Programming': 'Computer Programming',
  'Diploma in Business Administration': 'Business Administration',
  'Diploma in Hospitality and Tourism Management': 'Hospitality and Tourism Management',
  'Diploma in Graphic Design': 'Graphic Design',
  'Diploma in Marketing and Digital Media': 'Marketing and Digital Media',
  'Diploma in Early Childhood Education': 'Early Childhood Education',
  'Diploma in Environmental Science and Sustainability': 'Environmental Science and Sustainability',
  'Diploma in Health Information Management': 'Health Information Management',
  'Diploma in Supply Chain and Logistics Management': 'Supply Chain and Logistics Management',
  'Diploma in Mechanical Engineering Technology': 'Mechanical Engineering Technology',
  'Diploma in Civil Engineering Technology': 'Civil Engineering Technology',
  'Diploma in Food Science Technology': 'Food Science Technology',
  'Diploma in Biotechnology': 'Biotechnology',
  'Diploma in Cybersecurity': 'Cybersecurity',
  'Diploma in Social Work and Community Development': 'Social Work and Community Development',
  'Diploma in Automotive Service Technology': 'Automotive Service Technology',
  'Diploma in Renewable Energy Technology': 'Renewable Energy Technology',
  'Diploma in Nursing and Patient Care': 'Nursing and Patient Care',
  'Diploma in Web Development and UI/UX Design': 'Web Development and UI/UX Design',
  'Diploma in Artificial Intelligence and Machine Learning': 'Artificial Intelligence and Machine Learning',
  'Bachelor of Science in Computer Science': 'Computer Science',
  'Bachelor of Science in Artificial Intelligence': 'Artificial Intelligence',
  'Bachelor of Science in Data Analytics': 'Data Analytics',
  'Bachelor of Science in Biotechnology': 'Biotechnology',
  'Bachelor of Science in Environmental Science': 'Environmental Science',
  'Bachelor of Science in Nursing': 'Nursing',
  'Bachelor of Science in Mechanical Engineering': 'Mechanical Engineering',
  'Bachelor of Science in Aerospace Engineering': 'Aerospace Engineering',
  'Bachelor of Arts in Political Science': 'Political Science',
  'Bachelor of Arts in Sociology': 'Sociology',
  'Bachelor of Arts in Media and Communication Studies': 'Media and Communication Studies',
  'Bachelor of Arts in International Relations': 'International Relations',
  'Bachelor of Business Administration (BBA)': 'Business Administration',
  'Bachelor of Commerce (B.Com)': 'Commerce',
  'Bachelor of Fine Arts in Visual Communication': 'Visual Communication',
  'Bachelor of Laws (LL.B.)': 'Laws',
  'Bachelor of Education (B.Ed.)': 'Education',
  'Bachelor of Psychology': 'Psychology',
  'Master of Science in Computer Science': 'Computer Science',
  'Master of Science in Artificial Intelligence': 'Artificial Intelligence',
  'Master of Science in Data Science': 'Data Science',
  'Master of Science in Biotechnology': 'Biotechnology',
  'Master of Science in Environmental Sustainability': 'Environmental Sustainability',
  'Master of Science in Nursing': 'Nursing',
  'Master of Science in Civil Engineering': 'Civil Engineering',
  'Master of Science in Mechanical Engineering': 'Mechanical Engineering',
  'Master of Science in Aerospace Engineering': 'Aerospace Engineering',
  'Master of Science in Software Engineering': 'Software Engineering',
  'Master of Business Administration (MBA)': 'Business Administration',
  'Master of Arts in Political Science': 'Political Science',
  'Master of Arts in Sociology': 'Sociology',
  'Master of Arts in Media and Communication Studies': 'Media and Communication Studies',
  'Master of Arts in International Relations': 'International Relations',
  'Master of Laws (LL.M.)': 'Laws',
  'Master of Education (M.Ed.)': 'Education',
  'Master of Public Policy and Governance': 'Public Policy and Governance',
  'Master of Fine Arts in Visual Communication': 'Visual Communication',
  'Master of Health Administration': 'Health Administration',
  'Diploma in Cybersecurity and IT Security': 'Cybersecurity and IT Security',
  'Diploma in Data Analytics': 'Data Analytics',
  'Diploma in Financial Management': 'Financial Management',
  'Diploma in Health Informatics': 'Health Informatics',
  'Diploma in Marketing and Digital Strategy': 'Marketing and Digital Strategy',
  'Diploma in Software Development': 'Software Development',
  'Diploma in Renewable Energy Systems': 'Renewable Energy Systems',
  'Diploma in Environmental Sustainability': 'Environmental Sustainability',
  'Diploma in Human Resource Management': 'Human Resource Management',
  'Diploma in Public Health and Policy': 'Public Health and Policy',
  'Diploma in Social Media Marketing': 'Social Media Marketing',
  'Diploma in Urban Planning': 'Urban Planning',
  'Diploma in Robotics and Automation': 'Robotics and Automation',
  'Diploma in Hotel and Hospitality Management': 'Hotel and Hospitality Management',
  'Postgraduate Diploma in Artificial Intelligence': 'Artificial Intelligence',
  'Postgraduate Diploma in Data Science': 'Data Science',
  'Postgraduate Diploma in Business Analytics': 'Business Analytics',
  'Postgraduate Diploma in Cybersecurity and Cloud Computing': 'Cybersecurity and Cloud Computing',
  'Postgraduate Diploma in Software Engineering': 'Software Engineering',
  'Postgraduate Diploma in Renewable Energy Systems': 'Renewable Energy Systems',
  'Postgraduate Diploma in Advanced Biotechnology': 'Advanced Biotechnology',
  'Postgraduate Diploma in Project Management': 'Project Management',
  'Postgraduate Diploma in Environmental Policy': 'Environmental Policy',
  'Postgraduate Diploma in Marketing and Digital Strategy': 'Marketing and Digital Strategy',
  'Postgraduate Diploma in Machine Learning and Deep Learning': 'Machine Learning and Deep Learning',
  'Postgraduate Diploma in Public Health Management': 'Public Health Management',
  'Postgraduate Diploma in Human Resource Management': 'Human Resource Management',
  'Postgraduate Diploma in Clinical Research': 'Clinical Research',
  'Postgraduate Diploma in International Business and Trade': 'International Business and Trade',
  'Postgraduate Diploma in Digital Media and Communication': 'Digital Media and Communication',
  'Postgraduate Diploma in Biomedical Sciences': 'Biomedical Sciences',
  'Postgraduate Diploma in Robotics and Intelligent Systems': 'Robotics and Intelligent Systems',
  'Bachelor of Science in Data Science': 'Data Science',
  'Bachelor of Science in Electrical Engineering': 'Electrical Engineering',
  'Bachelor of Science in Mathematics and Statistics': 'Mathematics and Statistics',
  'Bachelor of Arts in Psychology': 'Psychology',
  'Bachelor of Fine Arts in Visual Arts and Design': 'Visual Arts and Design',
  'Master of Science in Electrical Engineering': 'Electrical Engineering',
  'Master of Science in Renewable Energy Systems': 'Renewable Energy Systems',
  'Master of Science in Robotics and Automation': 'Robotics and Automation',
  'Master of Science in Urban Planning': 'Urban Planning',
  'Diploma in Civil Engineering': 'Civil Engineering',
  'Diploma in Information Technology': 'Information Technology',
  'Diploma in Health Sciences': 'Health Sciences',
  'Diploma in Environmental Science': 'Environmental Science',
  'Diploma in Digital Marketing': 'Digital Marketing',
  'Diploma in Project Management': 'Project Management',
  'Diploma in Event Management': 'Event Management',
  'Diploma in Sports Management': 'Sports Management',
  'Diploma in Construction Technology': 'Construction Technology',
  'Postgraduate Diploma in Data Science and Analytics': 'Data Science and Analytics',
  'Postgraduate Diploma in Cybersecurity and IT Governance': 'Cybersecurity and IT Governance',
  'Postgraduate Diploma in Health Informatics': 'Health Informatics',
  'Postgraduate Diploma in Public Health and Community Care': 'Public Health and Community Care',
  'Postgraduate Diploma in Environmental Sustainability': 'Environmental Sustainability',
  'Postgraduate Diploma in Robotics and Automation': 'Robotics and Automation',
  'Postgraduate Diploma in Urban Planning': 'Urban Planning',
  'Postgraduate Diploma in Education Leadership': 'Education Leadership',
  'Postgraduate Diploma in Disaster Risk Reduction': 'Disaster Risk Reduction',
  'Postgraduate Diploma in Sports Analytics': 'Sports Analytics',
  'Bachelor of Information Technology': 'Information Technology',
  'Bachelor of Science in Marine Biology': 'Marine Biology',
  'Bachelor of Science in Renewable Energy Technology': 'Renewable Energy Technology',
  'Bachelor of Music': 'Music',
  'Bachelor of Engineering in Software Engineering': 'Software Engineering',
  'Master of Science in Data Science and Analytics': 'Data Science and Analytics',
  'Master of Public Health': 'Public Health',
  'Master of Science in Nanotechnology': 'Nanotechnology',
  'Master of Science in Marine and Coastal Science': 'Marine and Coastal Science',
  'Master of Fine Arts in Design and Visual Communication': 'Design and Visual Communication',
  'Master of Urban and Regional Planning': 'Urban and Regional Planning',
  'Master of Science in Food Science and Technology': 'Food Science and Technology',
  'Master of Science in Climate Change and Policy': 'Climate Change and Policy',
  'Master of Sports Management': 'Sports Management',
  'Diploma in Tourism and Hospitality Management': 'Tourism and Hospitality Management',
  'Diploma in Creative Writing and Journalism': 'Creative Writing and Journalism',
  'Diploma in Construction Management': 'Construction Management',
  'Postgraduate Diploma in Cybersecurity': 'Cybersecurity',
  'Postgraduate Diploma in Public Health': 'Public Health',
  'Postgraduate Diploma in Marketing and Digital Media': 'Marketing and Digital Media',
  'Postgraduate Diploma in Tourism Management': 'Tourism Management',
  'Postgraduate Diploma in Sports Science': 'Sports Science',
  'Postgraduate Diploma in Food Technology': 'Food Technology',
  'Bachelor of Science in Renewable Energy Systems': 'Renewable Energy Systems',
  'Bachelor of Science in Food Science and Technology': 'Food Science and Technology',
  'Bachelor of Science in Applied Physics': 'Applied Physics',
  'Bachelor of Tourism and Hospitality Management': 'Tourism and Hospitality Management',
  'Master of Science in Marine Biology': 'Marine Biology',
  'Master of Science in Food Technology': 'Food Technology',
  'Master of Science in Applied Physics': 'Applied Physics',
  'Master of Fine Arts in Visual Arts and Design': 'Visual Arts and Design',
  'Diploma in Artificial Intelligence': 'Artificial Intelligence',
  'Diploma in Environmental Management': 'Environmental Management',
  'Diploma in Health and Social Care': 'Health and Social Care',
  'Diploma in International Relations': 'International Relations',
  'Diploma in Biomedical Sciences': 'Biomedical Sciences',
  'Postgraduate Diploma in Artificial Intelligence and Machine Learning': 'Artificial Intelligence and Machine Learning',
  'Postgraduate Diploma in Urban Planning and Development': 'Urban Planning and Development',
  'Postgraduate Diploma in Cybersecurity and IT Security': 'Cybersecurity and IT Security',
  'Postgraduate Diploma in International Law': 'International Law',
  'Postgraduate Diploma in Public Policy and Governance': 'Public Policy and Governance',
  'Postgraduate Diploma in Biomedical Engineering': 'Biomedical Engineering',
  'Postgraduate Diploma in Human Rights and Ethics': 'Human Rights and Ethics',
  'Postgraduate Diploma in Creative Writing': 'Creative Writing',
  'Bachelor of Fine Arts in Visual Arts': 'Visual Arts',
  'Bachelor of Science in Physics': 'Physics',
  'Bachelor of Arts in Philosophy': 'Philosophy',
  'Master of Science in Climate Change and Risk Management': 'Climate Change and Risk Management',
  'Master of Science in Biomedical Engineering': 'Biomedical Engineering'
}