export const universitiesByCountry = {
    Germany: [
      { universityName: "Technische Universität München", imgPath: "image-72-3-1024x505.png" },
      { universityName: "Ludwig-Maximilians-Universität München", imgPath: "image-102-1024x453.png" },
      { universityName: "Ruprecht-Karls-Universität Heidelberg", imgPath: "image-1-3-1024x505.png" },
      { universityName: "Humboldt-Universität zu Berlin", imgPath: "image-2-4-1024x505.png" },
      { universityName: "Freie Universität Berlin", imgPath: "image-3-4-1024x505.png" },
      { universityName: "Universität Freiburg", imgPath: "image-4-3-1024x505.png" },
      { universityName: "Universität Tübingen", imgPath: "image-5-4-1024x505.png" },
      { universityName: "Rheinische Friedrich-Wilhelms-Universität Bonn", imgPath: "image-6-4-1024x453.png" },
      { universityName: "Universität Hamburg", imgPath: "image-7-4-1024x505.png" },
      { universityName: "Universität Göttingen", imgPath: "image-8-3-1024x505.png" },
      { universityName: "Universität Mannheim", imgPath: "image-9-3-1024x505.png" },
      { universityName: "RWTH Aachen University", imgPath: "image-15-3-1024x505.png" },
      { universityName: "Universität Stuttgart", imgPath: "image-16-3-1024x505.png" },
      { universityName: "Universität Erlangen-Nürnberg", imgPath: "image-17-3-1024x505.png" },
      { universityName: "Universität Ulm", imgPath: "image-18-3-1024x505.png" },
      { universityName: "Universität Leipzig", imgPath: "image-19-3-1024x505.png" },
      { universityName: "Universität Düsseldorf", imgPath: "image-20-3-1024x505.png" },
      { universityName: "Universität Konstanz", imgPath: "image-21-3-1024x505.png" },
      { universityName: "Karlsruhe Institute of Technology - KIT", imgPath: "image-22-3-1024x505.png" },
      { universityName: "Technische Universität Dresden", imgPath: "image-24-3-1024x505.png" }
    ],
    
    Canada: [
      { universityName: "University of Toronto", imgPath: "Rectangle-496-5.png" },
      { universityName: "University of British Columbia", imgPath: "image-72.png" },
      { universityName: "McGill University", imgPath: "image-74.png" },
      { universityName: "University of Alberta", imgPath: "image-75.png" },
      { universityName: "University of Montreal", imgPath: "image-76.png" },
      { universityName: "McMaster University", imgPath: "image-77.png" },
      { universityName: "University of Waterloo", imgPath: "image-78.png" },
      { universityName: "University of Western Ontario", imgPath: "image-79.png" },
      { universityName: "Queen’s University", imgPath: "image-80.png" },
      { universityName: "University of Calgary", imgPath: "image-81.png" },
      { universityName: "Dalhousie University", imgPath: "image-92.png" },
      { universityName: "University of Ottawa", imgPath: "image-83.png" },
      { universityName: "University of Victoria", imgPath: "image-84.png" },
      { universityName: "Simon Fraser University", imgPath: "image-85.png" },
      { universityName: "Université Laval", imgPath: "image-86.png" },
      { universityName: "York University", imgPath: "image-87.png" },
      { universityName: "University of Saskatchewan", imgPath: "image-88.png" },
      { universityName: "Carleton University", imgPath: "image-89.png" },
      { universityName: "University of Guelph", imgPath: "image-90.png" },
      { universityName: "Université de Sherbrooke", imgPath: "image-91.png" }
    ],
  
    USA: [
      { universityName: "Harvard University", imgPath: "Rectangle-496-5.png" },
      { universityName: "Stanford University", imgPath: "image-45.png" },
      { universityName: "Massachusetts Institute of Technology (MIT)", imgPath: "image-1-2.png" },
      { universityName: "California Institute of Technology (Caltech)", imgPath: "image-2-3.png" },
      { universityName: "University of Chicago", imgPath: "image-3-3.png" },
      { universityName: "Princeton University", imgPath: "image-4-2.png" },
      { universityName: "Columbia University", imgPath: "image-5-3.png" },
      { universityName: "University of Pennsylvania", imgPath: "image-6-3.png" },
      { universityName: "Yale University", imgPath: "image-7-3.png" },
      { universityName: "University of California, Berkeley", imgPath: "image-8-2.png" },
      { universityName: "University of California, Los Angeles", imgPath: "image-9-2.png" },
      { universityName: "University of Michigan, Ann Arbor", imgPath: "image-10-2.png" },
      { universityName: "Johns Hopkins University",imgPath: "image-11-2.png" },
      { universityName: "Northwestern University", imgPath: "image-12-2.png" },
      { universityName: "Duke University", imgPath: "image-13-2.png" },
      { universityName: "Cornell University", imgPath: "image-14-2.png" },
      { universityName: "New York University (NYU)", imgPath: "image-15-2.png" },
      { universityName: "University of Southern California", imgPath: "image-16-1.png" },
      { universityName: "Carnegie Mellon University", imgPath: "image-17-1.png" },
      { universityName: "University of Washington, Seattle", imgPath: "image-18-1.png" }
    ],
    Australia: [
        { universityName: "Australian National University", imgPath: "image-96.png" },
        { universityName: "University of Melbourne", imgPath: "image-97-1.png" },
        { universityName: "University of Sydney", imgPath: "image-98-1.png" },
        { universityName: "University of Queensland", imgPath: "image-99-1.png" },
        { universityName: "University of New South Wales", imgPath: "image-100-1.png" },
        { universityName: "Monash University", imgPath: "image-2024-10-13T212600.176.png" },
        { universityName: "University of Western Australia", imgPath: "image-2024-10-13T212604.108.png" },
        { universityName: "University of Adelaide", imgPath: "image-2024-10-13T212606.947.png" },
        { universityName: "University of Technology Sydney", imgPath: "image-2024-10-13T212609.949.png" },
        { universityName: "University of Canberra", imgPath: "image-2024-10-13T212613.860.png" },
        { universityName: "Macquarie University", imgPath: "image-2024-10-13T212616.886.png" },
        { universityName: "Queensland University of Technology", imgPath: "image-2024-10-13T212619.686.png" },
        { universityName: "RMIT University", imgPath: "image-2024-10-13T212624.361.png" },
        { universityName: "University of Wollongong", imgPath: "image-2024-10-13T212627.691.png" },
        { universityName: "Curtin University", imgPath: "image-2024-10-13T212631.427.png" },
        { universityName: "Deakin University", imgPath: "image-2024-10-13T212634.823.png" },
        { universityName: "University of Newcastle", imgPath: "image-2024-10-13T212637.775.png" },
        { universityName: "Griffith University", imgPath: "image-2024-10-13T212640.629.png" },
        { universityName: "La Trobe University", imgPath: "image-2024-10-13T212644.543.png" },
        { universityName: "University of Tasmania", imgPath: "image-2024-10-13T212647.564.png" }
      ],
    
     'New Zealand': [
        { universityName: "University of Auckland", imgPath: "image-40-1.png" },
        { universityName: "University of Otago", imgPath: "image-41-1.png" },
        { universityName: "Victoria University of Wellington", imgPath: "image-42-1.png" },
        { universityName: "University of Canterbury", imgPath: "image-43-1.png" },
        { universityName: "Massey University", imgPath: "image-44-1.png" },
        { universityName: "University of Waikato", imgPath: "image-45-1.png" },
        { universityName: "Lincoln University", imgPath: "image-46-1.png" },
        { universityName: "Auckland University of Technology", imgPath: "image-47-1.png" }
      ],
    
      UK: [
        { universityName: "University of Oxford", imgPath: "image-19-1.png" },
        { universityName: "University of Cambridge", imgPath: "image-20-1.png" },
        { universityName: "Imperial College London", imgPath: "image-21-1.png" },
        { universityName: "London School of Economics and Political Science (LSE)", imgPath: "image-22-1.png" },
        { universityName: "University College London", imgPath: "image-23-1.png" },
        { universityName: "University of Edinburgh", imgPath: "image-24-1.png" },
        { universityName: "University of Manchester", imgPath: "image-25-1.png" },
        { universityName: "King’s College London", imgPath: "image-26-1.png" },
        { universityName: "University of Warwick", imgPath: "image-27-1.png" },
        { universityName: "University of Bristol", imgPath: "image-28-1.png" },
        { universityName: "University of Glasgow", imgPath: "image-29-1.png" },
        { universityName: "University of Birmingham", imgPath: "image-30-1.png" },
        { universityName: "University of Sheffield", imgPath: "image-31-2.png" },
        { universityName: "University of Southampton", imgPath: "image-32-1.png" },
        { universityName: "University of Leeds", imgPath: "image-33-1.png" },
        { universityName: "University of York", imgPath: "image-34-1.png" },
        { universityName: "University of Exeter", imgPath: "image-35-1.png" },
        { universityName: "University of St Andrews", imgPath: "image-36-1.png" },
        { universityName: "University of Nottingham", imgPath: "image-39-1.png" },
        { universityName: "University of Durham", imgPath: "image-37-1.png" }
      ]
  };
  
  console.log(universitiesByCountry);
  